import { ClerkProvider } from "@clerk/nextjs"
import type { Metadata } from "next"
import { Roboto } from "next/font/google"
import { Toaster } from "sonner"
import { DocumentProvider } from "./_context/document"
import "./globals.css"

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
})

export const metadata: Metadata = {
  title: "Doc Control",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <ClerkProvider>
          <DocumentProvider>{children}</DocumentProvider>

          <Toaster richColors />
        </ClerkProvider>
      </body>
    </html>
  )
}
